### ISSUE TITLE
How to identify which identifier is which device?

### ISSUE THREAD

**Issue by reedy** [zxdavb/ramses_cc#113]
How do you identify which found device is which in practice?

While I understand the point of the `known_list` etc, it seems prudent to label the ID with at least a comment of which sensor is which (seems to be commonly shown in various cases where people post their configs); it's just not obvious how to work out which is which to map them.

Happy to document it in the wiki :)

Feels like a table of prefixes, and what they're known to be would be useful too..

**Comment by zxdavb** [comment]
I can see you've read the wiki, so I've tweaked it to make things more clear. Look here: https://github.com/zxdavb/ramses_cc/wiki/2.-configuration.yaml#known_list

... and here: https://github.com/zxdavb/ramses_cc/wiki/2.-I'm-stuck:-Help-me

I think the latter has the answer you need.

This is not a support forum: if you're still stuck, ask here: https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/3881

**Comment by reedy** [comment]
Cheers, FWIW on https://github.com/zxdavb/ramses_cc/wiki/2.-I'm-stuck:-Help-me

> If you still have issues, and can't find an answer on this wiki, reach out on the HA forum, or raise an issue on this repo.

I'd already got the list of ID's, and mostly worked out what was what, it's just the many `04:` (HR92) devices, and working out which is which room.

A bit more searching (finding the right terms is hard sometimes!), and I've updated the wiki https://github.com/zxdavb/ramses_cc/wiki/2.-I'm-stuck:-Help-me/_compare/b2740a4a1e9e28b29394e70aa380fa71916bdab1...b17c3d85969c6ec160e97f3c4f3b8d3662504478

Thanks again!

**Comment by zxdavb** [comment]
> If you still have issues, and can't find an answer on this wiki, reach out on the HA forum, or raise an issue on this repo.

Fair enough!

Thanks for updating the wiki.
