### ISSUE TITLE
Making TRVs and Thermostats devices

### ISSUE THREAD

**Issue by markjsmith** [zxdavb/ramses_cc#138]
Hi, not sure if this is possible or of value to others but
I've been building Battery Notes into my install, which adds battery info to devices.
I would see this as a useful addition to record battery replacement dates etc to preempt battery failure. 
This matters more as faults don't currently show in the Ramses integration.
What do you think?

**Comment by zxdavb** [comment]
Please discuss this on the [HA forum](https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/4062)

The **evohome** integration is about to significantly improve reporting of errors, such as low batteries.

The **ramses_cc** integration does have battery sensors for devices that report it.
