### ISSUE TITLE
Logo for Home Assistant Branding

### ISSUE THREAD

**Issue by trvrnrth** [zxdavb/ramses_cc#144]
With the introduction of config flow in #121 the integration and devices now show a component logo which will need adding to https://github.com/home-assistant/brands

Since Ramses was a pharaoh I wondered if we could have some fun with that. Here's a first draft of an idea I had:

![ramses](https://github.com/zxdavb/ramses_cc/assets/367121/0bbf14bc-8515-4ac5-a129-b17cc1594585)

It's perhaps a little menacing at the moment and might need some simplifying to work well at the 24px for individual devices but wanted to get thoughts on the general idea before doing any refinement.

**Comment by trvrnrth** [comment]
Couldn't help playing around a bit more. Here's a more refined version that renders better at smaller sizes.

![ramses_v7](https://github.com/zxdavb/ramses_cc/assets/367121/f1c6dceb-0f18-48f3-8286-4ad1f99fce4b)

![ramsesv7_64](https://github.com/zxdavb/ramses_cc/assets/367121/3fa869ea-d8a8-441b-8e60-8329a5ef90b0)

![ramsesv7_24](https://github.com/zxdavb/ramses_cc/assets/367121/9e6d857c-d8b3-4509-aa3c-3b6436263f65)

**Comment by trvrnrth** [comment]
Some further adjustments to improve rendering at small sizes:

![ramses_v8](https://github.com/zxdavb/ramses_cc/assets/367121/bb8fd987-031f-4250-b8e9-3c179eb3322f)

![ramsesv8_64](https://github.com/zxdavb/ramses_cc/assets/367121/8ce11e9c-0a8d-4fa3-8ae1-b14cfb22919e)

![ramsesv8_24](https://github.com/zxdavb/ramses_cc/assets/367121/3eb77228-d808-4189-b7a8-6c0f38e55e78)

**Comment by zxdavb** [comment]
I think it looks great!

**Comment by jrb80** [comment]
It looks good, I do wonder whether this link to Egyptian Dynasty was intended or just coincidence. Fyi, 

RAMSES = **R**oom **A**partment **M**anager **Sy**stem **E**ngineering **S**pecification

**Comment by trvrnrth** [comment]
> It looks good, I do wonder whether this link to Egyptian Dynasty was intended or just coincidence. Fyi,
> 
> RAMSES = **R**oom **A**partment **M**anager **Sy**stem **E**ngineering **S**pecification

I have no idea at all, but it feels a bit backronymy and If there isn't at least some internal egyptian themed swag somewhere someone missed a trick!

**Comment by lloyda** [comment]
Saw this in HACS this morning - looks great.
