### ISSUE TITLE
Adding 1FC9 binding messages to ramses_cc_message HA events

### ISSUE THREAD

**Issue by Onl1ne1373** [zxdavb/ramses_cc#151]
I created a Home Assistant Blueprint for handling Spider messages. It would be better if Spider Thermostat was fully supported in ramses_rf, but for now it works for me.

Blueprint: https://raw.githubusercontent.com/Onl1ne1373/home-assistant-blueprints/main/spider.yaml

What this blueprint does is that it listens to 01FF and 1FC9 messages and handles auto binding and RP messages.
It also listens to a HA Generic Thermostat for the setpoint. 

Setpoint messages work if I change the parser like in ramses_rf issue: https://github.com/zxdavb/ramses_rf/issues/101
The `1FC9` message do not work because I do not receive these messages via ramses_cc_message event.
It would be very handy if I could receive them. I don't think it is a parser issue, but more a handling one.

I use message_events: `"RQ.* (01FF|1FC9)"`

I will look further into it, but it would be very nice if you could add 1FC9 binding messages also to ramses_cc_message events.

**Comment by zxdavb** [comment]
I woudl use:
```yaml
ramses_cc:
  advanced_features:
    message_events: "RQ.* (01FF|1FC9) "
```

Note the space after `1FC9)`

**Comment by zxdavb** [comment]
```
>>> regex
re.compile('I.* (000A|0418|1F09|1FC9) ')

>>> regex.match("I 1FC9 ")
<re.Match object; span=(0, 7), match='I 1FC9 '>

>>> regex.match(" I 1FC9 ")

```

**Comment by zxdavb** [comment]
@Onl1ne1373 

An `RQ|1FC9` is unusual. DO you mean `I|1FC9` (or `W|1FC9`), or `1F09`?

Or can you provide more information?

**Comment by Onl1ne1373** [comment]
Sorry I changed it, it was "(I|RP).* (01FF|1FC9)".
The extra space is nice after the message type, that way the start of payload does not match.

But indeed, RQ of 01FF and I for the 1FC9. So "(RQ.* 01FF |I.* 1FC9 )" would be there right one.

**Comment by Onl1ne1373** [comment]
Changed it to "(RQ.* 01FF |I.* 1FC9 )", but I do not get events in Home Assistant. Using the development tools.



```log
2024-02-04T16:53:50.019116 076  I --- 21:033394 --:------ 21:033394 1FC9 030 0022C95482720022F154827200000E5482720110E0548272001FC9548272
```

**Comment by Onl1ne1373** [comment]
Changed regex.match to regex.search in __init__.py and it works, I get the events! Thank you!

**Comment by zxdavb** [comment]
Simply use this for now: `"(RQ.* 01FF | I.* 1FC9 )"`
