### ISSUE TITLE
Config flow: Clear cache dialog box is potentially confusing

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/ramses_cc#155]
Regarding the configuration dialog box, below>

These switches do not clear the cache (although that is the likely effect).

Instead, they prevent these cached data (schema, packets) from being loaded during startup of the integration.

Suggest:
 - Title: Startup behaviour (or Restore cache)
 - Restore the cached schema
 - Restore the cached packets

Perhaps a note could be added at the bottom:
 - The schema / packets are always saved periodically, this behaviour is not configurable.

![image](https://github.com/zxdavb/ramses_cc/assets/6784264/6629c163-5075-426b-93e4-16af74b6aa91)

**Comment by zxdavb** [comment]
@trvrnrth FYI: I am happy to make these changes - give you first refusal?

**Comment by trvrnrth** [comment]
They do actually immediately clear the cache and reload the integration now.

**Comment by zxdavb** [comment]
Oh - perhaps a note at the bottom to say will clear & reload (so no need to restart HA)?

It's just that the behaviour is so different to before.

**Comment by trvrnrth** [comment]
We could probably put a step description in with a bit of extra guidance. It'd do no harm.
