### ISSUE TITLE
The gateway type is not determinable, will assume evofw3

### ISSUE THREAD

**Issue by smartypantsuk** [zxdavb/ramses_cc#157]
Latest version, and I get this in the logs now:
```
/dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT5S4V48-if00-port0: the gateway type is not determinable, will assume evofw3, TIP: specify the serial port by-id (i.e. /dev/serial/by-id/usb-...)
```
As you can see, I'm already using /dev/serial/by-id...
It says treating as an evofw3 device, however, I actually have a **serial** HGI80 connected via usb adapter. It works fine but latest updates treat it as an evofw3.

Can we have a manual switch to tell it what it is?

**Comment by zxdavb** [comment]
There are no current plans for a 'manual switch' 
 - **HGI80**s are quite uncommon, compared to **evofw3**-based dongles
 - **HGS80**s are be even more rare, and will be considered edge-cases
 - **ramses_rf** will remain largely functional, even if a **HGI80** is detected as an **evofw3**

**Comment by zxdavb** [comment]
However, this error message has been improved so that it doesn't suggest to use `by-id` when you are using `by-id`
