### ISSUE TITLE
implements HVACMode(s): heat, off, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature.

### ISSUE THREAD

**Issue by keesma** [zxdavb/ramses_cc#162]
**Describe the bug**
I found this in the home assistant log after startup.
This might be related to issue #156
```
2024-02-07 23:33:02.238 WARNING (MainThread) [homeassistant.components.climate] Entity climate.01:026398 (<class 'custom_components.ramses_cc.climate.RamsesController'>) implements HVACMode(s): heat, off, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/zxdavb/ramses_cc/issues
```
HVAC is a Buva Boxstream (in fact two of them are connected). I only have two remote controls to change the speed and a timer.

**To Reproduce**
Restart home assistant (?)

**Expected behavior**
No warning message.

**Please complete the following information:**
 - see issue #156 
 - See above
 - contemporaneous portion of the **[packet log 20240207-2.txt](https://github.com/zxdavb/ramses_cc/files/14202518/packet.log.20240207-2.txt)**

**Screenshots**
n/a

**Additional context**
HVAC Boxstream

**Comment by peternash** [comment]
I'm seeing this warning message too.  I suspect it's due to upgrading to HA 2024.2.x and this 10 month deprecation warning [https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded]

**Comment by networkerict** [comment]
Seeing similar message: Entity climate.01:109777 (<class 'custom_components.ramses_cc.climate.RamsesController'>) implements HVACMode(s): heat, off, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/zxdavb/ramses_cc/issues

01:109777 is my Evohome controller

**Comment by zxdavb** [comment]
> I'm seeing this warning message too. I suspect it's due to upgrading to HA 2024.2.x and this 10 month deprecation warning

Is the correct answer.

Please ignore this error message for now.
