### ISSUE TITLE
Hot Water device is not being named

### ISSUE THREAD

**Issue by brucemiranda** [zxdavb/ramses_cc#166]
ramses_cc does not appear to be naming the Hot Water device correctly in 0.41.7

As a result when you look at the Devices listed under the ramses_cc integration you have a device called "Heat Demand" and within it, you have a Controls called "Unnamed device".

![Screenshot_20240212_191657_Home Assistant](https://github.com/zxdavb/ramses_cc/assets/7365852/d24dfeb2-2034-458d-baeb-c96a2c22b69e)

![Screenshot_20240212_193118_Home Assistant](https://github.com/zxdavb/ramses_cc/assets/7365852/44b07ac1-5a22-4e63-ad07-3f7844dd9ba5)

**Comment by zxdavb** [comment]
This is related to #168 - I do not expect this issue in **0.31.x**.

**Comment by brucemiranda** [comment]
Now fixed in 0.41.20. Sensor named as "Stored HW"
