### ISSUE TITLE
The config flow fields discards comments

### ISSUE THREAD

**Issue by brucemiranda** [zxdavb/ramses_cc#167]
If any of the data within the config flow is commented out, then those commented lines are lost forever as the config flow discards the comments and just updates the data fields with the uncommented lines.

See example below. Within the Schema section the zone 07 values were present and commented out. But then on reload, those commented lines are lost forever. And there is no trace of any information related to zone 07.

![Screenshot_20240212_203010_Home Assistant](https://github.com/zxdavb/ramses_cc/assets/7365852/cf28066f-94d5-4451-9312-823a491f20d2)

**Comment by zxdavb** [comment]
Closing as **wont_fix** (cant_fix).
