### ISSUE TITLE
ramses_rf transmits too many packets per unit time

### ISSUE THREAD

**Issue by brucemiranda** [zxdavb/ramses_cc#180]
When the offical Honeywell HGI80 is used as the serial device,  ramses_cc or ramses_rf are stressing it too much and the HGI80 hits a max duty cycle and shuts down. This is an inbuilt function designed to stop RF jamming. 

ramses_cc and ramses_rf need to respect the etiquette of RF communications and be a bit less chatty. The HGI80 has to be the gold standard. 

Currently using ramses_cc 0.41.7 with a manually adjusted ramses_rf 0.31.13

**Comment by zxdavb** [comment]
IMO, there is no evidence that **ramses_rf** is exceeding the HGI80 duty cycle:
 - unless it is abused by the user, e.g. multiple back-to-back restarts of HA with the cache disabled

**Comment by brucemiranda** [comment]
ramses_cc should slow down it's queries made

**Comment by zxdavb** [comment]
All the **HGI80** (868.3 MHz) docs I've seen do not specify its duty cycle, but my understanding from the [ETSI EN300.220-2](https://www.etsi.org/deliver/etsi_en/300200_300299/30022002/03.02.01_60/en_30022002v030201p.pdf) standard is that anything in band M (868.0-868.6 MHz), the duty cycle limit should be 1%.

Reference: https://www.thethingsnetwork.org/docs/lorawan/duty-cycle/

I appreciate that **ramses_rf** is very chatty, but this is a trade-off between a lower duty cycle and having convergent data...

A lot of work has gone into reducing the Tx rate as much as possible:
 - for example, **ramses_rf** imposes a duty cycle of 1% per 60s

There are opportunities for further gains in the future (i.e. eavesdropping `3220` packets between the controller and the OTB in preference to sending periodic `3220|RQ|OTBs` - this is planned.

**Comment by zxdavb** [comment]
> **ramses_cc** should slow down it's queries made

It would be useful to hear your thoughts on why you believe the rate is excessive?

What Tx rate would be acceptable?
