### ISSUE TITLE
Packet log not rotating in config_flow

### ISSUE THREAD

**Issue by ghoti57** [zxdavb/ramses_cc#187]
packet.log doesn't seem to be rotating.
The rotation appears to have stopped when I switched form 0.31.x to 0.41.x

configuration.yaml contained
```
ramses_cc:
  ..
  packet_log: evohome/packet.log
  ..
```  
  core.config_entries contains
```
            "packet_log": {
            "file_name": "evohome/packet.log"
          },
```

**Comment by Kars-de-Jong** [comment]
I noticed this too. When you look at the setting dialog it does show 7, but is not actually saved (probably because it is the default). And apparently the default behaviour changed to "no rotation" instead of 7.  I solved it by setting it to 8 and then back to 7 again.

**Comment by zxdavb** [comment]
I have identified the problem. Fix coming. 

Until then, you can enter this (i.e. explicitly specify the rotation policy), as a workaround:
```json
"packet_log": {
    "file_name": "packet.log", 
    "rotate_backups": 7
}
```

**Comment by zxdavb** [comment]
I believe this is now fixed.
