### ISSUE TITLE
Warning from Home Assistant 2024.5.5 log: "Detected that custom integration 'ramses_cc' accesses hass.helpers.storage"

### ISSUE THREAD

**Issue by acseven** [zxdavb/ramses_cc#188]
On HA 2024.5.5, there's this warning message in the log:

> 2024-05-28 21:55:38.621 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'ramses_cc' accesses hass.helpers.storage. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from storage directly at custom_components/ramses_cc/config_flow.py, line 554: store: Store = self.hass.helpers.storage.Store(STORAGE_VERSION, STORAGE_KEY), please create a bug report at https://github.com/zxdavb/ramses_cc/issues

**Comment by zxdavb** [comment]
I suspect you are using an older version of this integration.
