### ISSUE TITLE
Ramses_CC stopped working after HA update 2024.8.2

### ISSUE THREAD

**Issue by Rincovanderbeek** [zxdavb/ramses_cc#199]
After installing home assistant 2024.8.2, ramses_cc stopped working.
It status not being able to setups, logs say something is not ik in the py files.

**Comment by zxdavb** [comment]
You have not provided enough information for me to be able to help you.

**Comment by Rincovanderbeek** [comment]
Hi,

Sorry for not reacties.
I just installed the net update of Ramses_cc and also the HA code update.
After that, all worked

Thanks for your support!

Op ma 26 aug. 2024 11:56 schreef David Bonnes ***@***.***>:
