### ISSUE TITLE
Evohome device communication communication fail issues.

### ISSUE THREAD

**Issue by awhatford** [zxdavb/ramses_cc#207]
I have set up as all default apart from setting up mqto as I am using a Ramses esp over mqto.
I have over the 1st 24 hours lost intermittent random devices from my Evohome I suspect that the Ramses cc is polling each device and then these devices are not bothering to talk to the evohome after that because of some battery saving timer ect.

I have tried disabling polling through haos setting devices in gui but in mqto listener I can still see tx messages so I am not optimistic that this will resolve the issue.

On reading the wiki I can see I can set disable sending to true unfortunately using the limited search feature in the native haos gui I can't find the corresponding line in the config flow file so guessing that was the historic config file any pointers would be welcome.

![Screenshot_20241006-230127.png](https://github.com/user-attachments/assets/b82a04cc-9cee-460a-b440-d74d9046d959)

![PXL_20241002_211802925.jpg](https://github.com/user-attachments/assets/41453aea-2689-455e-b31d-9008f860f868)

**Comment by zxdavb** [comment]
> I have over the 1st 24 hours lost intermittent random devices from my Evohome I suspect that the Ramses cc is polling each device and then these devices are not bothering to talk to the evohome after that because of some battery saving timer ect.

**ramses_rf** _does not_ poll _any_ battery-powered devices (e.g. TRVs, thermostats and CS92As).

It will only poll the controller, any BDR91A/Ts, and any UFH controllers.

**Comment by zxdavb** [comment]
closing.
