### ISSUE TITLE
Can't install ramses_cc: `Unable to install package ramses-rf==...`

### ISSUE THREAD

**Issue by hermanbanken** [zxdavb/ramses_cc#211]
**Describe the bug**
Can't install ramses 0.42.0 because of python error.

From the HA logs:
```
Unable to install package ramses-rf==0.42.0: ERROR: Cannot install ramses-rf==0.42.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to HACS
2. Add repository https://github.com/zxdavb/ramses_cc/
3. Go to Integrations and add Ramses integration 
4. Dialog about wizard ends with 500 error

**Expected behavior**
Installation working

**Screenshots**
none

**Additional context**
HA version: 2024.2.2
Hardware: freshly unpacked Ramses ESP from IndaloTech
Logs:
```
Logger: homeassistant.util.package
Source: util/package.py:122
First occurred: 09:08:38 (3 occurrences)
Last logged: 09:08:45

Unable to install package ramses-rf==0.42.0: ERROR: Cannot install ramses-rf==0.42.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by zxdavb** [comment]
Please upgrade HA to the latest version and try again.

If that doesn't work, please provide more information (I think you have not provided all the error log).

**Comment by Ozzy94** [comment]
@hermanbanken 

how did you eventually solved this issue?
im having the same problem.

kind regards

Oscar
