### ISSUE TITLE
'ramses_cc' registers an entity service with a non entity service schema

### ISSUE THREAD

**Issue by donaldwpage** [zxdavb/ramses_cc#218]
system log reported
Detected that custom integration 'ramses_cc' registers an entity service with a non entity service schema

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 19:45:10 (3 occurrences)
Last logged: 19:59:03

Detected that custom integration 'ramses_cc' registers an entity service with a non entity service schema at custom_components/ramses_cc/climate.py, line 113: platform.async_register_entity_service(k, v, f"async_{k}"). This will stop working in Home Assistant 2025.9, please create a bug report at https://github.com/zxdavb/ramses_cc/issues
Detected that custom integration 'ramses_cc' registers an entity service with a non entity service schema at custom_components/ramses_cc/water_heater.py, line 59: platform.async_register_entity_service(k, v, f"async_{k}"). This will stop working in Home Assistant 2025.9, please create a bug report at https://github.com/zxdavb/ramses_cc/issues
Detected that custom integration 'ramses_cc' sets option flow config_entry explicitly, which is deprecated at custom_components/ramses_cc/config_flow.py, line 501: self.config_entry = entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/zxdavb/ramses_cc/issues

**Please complete the following information:**
 - `ramses_cc:` section from **configuration.yaml**
 - not used
 - contemporaneous portion of the **home-assistant.log**
 - contemporaneous portion of the **packet.log**

**Comment by donaldwpage** [comment]
gateway_config
disable_discovery: false
disable_qos: false
disable_sending: false
enable_eavesdrop: false

schema:
"01:108199": {}

known_device_ids:
"01:108199": {}
"02:022960": {}
"04:024890": {}
"04:049506": {}
"04:112432": {}
"04:123648": {}
"04:123650": {}
"04:123652": {}
"04:123654": {}
"04:125369": {}
"04:246790": {}
"07:030355": {}
"13:142019": {}
"13:181949": {}
"18:069148":
alias: evofw3
class: HGI
"34:007977": {}
"34:009973": {}

**Comment by RedEarth1** [comment]
same as #205 ?

**Comment by zxdavb** [comment]
yes - closing this in favour of that
