### ISSUE TITLE
Unable to install latest beta version using HACS as a fresh install

### ISSUE THREAD

**Issue by Kars-de-Jong** [zxdavb/ramses_cc#45]
When selecting a beta version, it can’t be installed. I believe this is caused by the rename of evohome_cc to ramses_cc. As you can see from the log below, HACS still tries to use the old name.

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.hacs
Source: custom_components/hacs/websocket.py:286 
Integration: HACS (documentation, issues) 
First occurred: 07:53:10 (6 occurrences) 
Last logged: 09:36:45

No manifest.json file found 'custom_components/evohome_cc/manifest.json'
```

**Comment by zxdavb** [comment]
This the one that currently says: **`DO NOT INSTALL`**?

Have a look at it's release notes, which include:
> Via HACS, check that Show beta versions is enabled for the Evohome RF integration. If you get an error message, No manifest.json file found, you can ignore it. Then restart HA.

**Comment by zxdavb** [comment]
You can by my first tester.

**Comment by Kars-de-Jong** [comment]
> This the one that currently says: **`DO NOT INSTALL`**? :)

Yes, that one. It’s a new install, so it doesn’t really matter for me. And I need the new Orcon stuff ;-)

> Have a look at it's release notes, which include:
> 
> > Via HACS, check that Show beta versions is enabled for the Evohome RF integration. If you get an error message, No manifest.json file found, you can ignore it. Then restart HA.

Hm, OK. I thought I already did that.

**Comment by Kars-de-Jong** [comment]
Nope, sorry, it doesn’t install it. It’s not in the `custom_components` folder, and doesn’t show up in integrations.

**Comment by zxdavb** [comment]
Hmmm.. Try installing **0.18.x** then upgrading?

**Comment by zxdavb** [comment]
I have a suspicion that this issue will persist until **0.20.x** is not a pre-release.

**Comment by Kars-de-Jong** [comment]
Can’t you make a new stable release with the rename?

**Comment by zxdavb** [comment]
No. it is too big a change - it wont be stable.

I have just tested the process I described: just enable **`Show beta versions`**, download **0.18.8** and reboot HA.

Have you tried it?

**Comment by Kars-de-Jong** [comment]
Yes, that procedure works. It does leave the old version in the evohome_cc directory, can I safely remove it?

**Comment by Kars-de-Jong** [comment]
I removed evohome_cc, because the logs of HA suggested the integration was started twice.

**Comment by zxdavb** [comment]
>It does leave the old version in the evohome_cc directory, can I safely remove it?

Correct x2: It will, and you can.

**Comment by zxdavb** [comment]
>I removed evohome_cc, because the logs of HA suggested the integration was started twice.

Hmmm... As long as the integration, `evohome_cc:`, is missing from **configuration.yaml**, then the **evohome_cc** folder will be ignored.
