### ISSUE TITLE
Migrate from 0.19.2 to 0.20.22g

### ISSUE THREAD

**Issue by mazzy89** [zxdavb/ramses_cc#51]
I'm currently running the latest release at the time of this writing that is 0.20.22g with the configuration from the 0.19.2. My configuration indeed is the one with `evohome_cc`.

I got updates into HACS throughout the summer and I haven't put much attention to the CHANGELOG. Then I got into this state.

Now I'm asking whether the process to follow to migrate successfully is the one from the release 0.20.15a. Could you confirm please @zxdavb?

**Comment by zxdavb** [comment]
This is not the appropriate place to ask fro user support.

Please pose your question here: https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/2812

I suggest you'll have better luck if you post your configuration, than not.

If the community doesn't chip in with an answer, I will.
