### ISSUE TITLE
Integration fails to load afrer upgrading to Home Assistant 2023.1.0

### ISSUE THREAD

**Issue by DJBenson** [zxdavb/ramses_cc#55]
Upgraded to Home Assistant 2023.1.0 this morning and the integration fails to load. There are two distinct errors in the logs;

![image](https://user-images.githubusercontent.com/1013909/210740427-d92bb4c3-5a4a-4961-bc91-b2fc0805eea5.png)

Both have the same error text;

`Logger: homeassistant.setup
Source: setup.py:340
First occurred: 08:49:19 (4 occurrences)
Last logged: 08:49:29

Unable to prepare setup for platform ramses_cc.sensor: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
Unable to prepare setup for platform ramses_cc.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).`

**Comment by lloyda** [comment]
Glad I spotted this before hitting the upgrade button.

I wonder if it is related to this change: https://github.com/home-assistant/core/pull/83131

**Comment by DJBenson** [comment]
I'm by no means a developer but could it be that TEMP_CELSIUS has been deprecated in favor of UnitOfTemperature.CELSIUS?

The integration is trying to reference TEMP_CELSIUS in homeassistant.components.sensor but it doesn't seem to exist in the latest version but UnitOfTemperature.CELSIUS does.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/const.py

**Comment by DJBenson** [comment]
> Glad I spotted this before hitting the upgrade button.
> 
> I wonder if it is related to this change: [home-assistant/core#83131](https://github.com/home-assistant/core/pull/83131)

Indeed - like I said, I'm no developer (I can fumble my way around code) but it looks to be the source of the issue.

**Comment by DJBenson** [comment]
Confirmed - I've just hacked a fix into my install and the integration comes back up.

Basically just replace all references of TEMP_CELSIUS to UnitOfTemperature.CELSIUS in both sensor.py and climate_hvac.py of the integration.

**Comment by networkerict** [comment]
> 

this didn't work for me. It got rid of one of the errors but not both. I also changed the file __init__.py because it als referenced the wrong value.

**Comment by DJBenson** [comment]
> > 
> 
> this didn't work for me. It got rid of one of the errors but not both. I also changed the file **init**.py because it als referenced the wrong value.
> 
> I still have:
> 
> Invalid config The following integrations and platforms could not be set up:
> 
> [ramses_cc](https://github.com/zxdavb/ramses_cc)

I've created a pull request for my changes - check the PR and see if you covered all instances.

**Comment by networkerict** [comment]
> > > 
> > 
> > 
> > this didn't work for me. It got rid of one of the errors but not both. I also changed the file **init**.py because it als referenced the wrong value.
> > I still have:
> > Invalid config The following integrations and platforms could not be set up:
> > [ramses_cc](https://github.com/zxdavb/ramses_cc)
> 
> I've created a pull request for my changes - check the PR and see if you covered all instances.

Manually copied the new files and all is working now - great! thanks for the swift resolution! much appreciated.

**Comment by sOckhamSter** [comment]
Yup, I've manually updated my files with your changes and it's working a treat, thanks for this :) Hopefully it gets merged very soon!

**Comment by msteenhuiz** [comment]
Got the patch file through 'https://patch-diff.githubusercontent.com/raw/zxdavb/ramses_cc/pull/56.patch' .
Applied it with 'sudo patch -p 1 -i 56.patch' in the data/config directory.
It's working for me.

**Comment by DJBenson** [comment]
Note: this fix only applies to the beta (0.22.X) channel.

Be careful that the latest fix pused today is a stable (0.20.X) release and "upgrading" from 0.22.X to 0.20.X may cause some issues as config changes have been made between stable and beta.
