### ISSUE TITLE
new stable version 0.20.22j is broken

### ISSUE THREAD

**Issue by mazzy89** [zxdavb/ramses_cc#57]
I've updated this morning to the new stable version [0.20.22j](https://github.com/zxdavb/ramses_cc/tree/0.20.22j) released. Unfortunately it is broken

```
Logger: homeassistant.setup
Source: setup.py:338 
First occurred: 9:59:07 AM (1 occurrences) 
Last logged: 9:59:07 AM

Unable to prepare setup for platform ramses_cc.sensor: Platform not found (cannot import name 'UnitOfTime' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

**Comment by DJBenson** [comment]
I have a different error - my config was working prior to this update;

`Invalid config for [ramses_cc]: expected bool for dictionary value @ data['ramses_cc']['advanced_features']['message_events']. Got 'RP.* 04:'. (See /config/configuration.yaml, line 60).`

**Comment by mazzy89** [comment]
which hassio version?

**Comment by DJBenson** [comment]
2023.1.1 - updated this morning (GMT).

**Comment by mazzy89** [comment]
interesting. I have updated to 2023.1.1 too and I do not have anymore that error. Further I do not see that error as well.

**Comment by DJBenson** [comment]
If I comment out the offending line the config checks out - but what changed is the question - that line has been in since I installed the package and I don't fully understand the implications of removing it.

![image](https://user-images.githubusercontent.com/1013909/210972179-166eaa6c-8246-4b4a-967d-5b16c438f8a0.png)

**Comment by lloyda** [comment]
@DJBenson What version did you upgrade from?

**Comment by DJBenson** [comment]
@lloyda I can't say specifically but the last release - I follow the beta channel and update every time there is a new release.

**Comment by DJBenson** [comment]
Removing the package entirely, commenting out the above and reinstalling worked. Just not sure what the absence of that config line means to my install.

**Comment by lloyda** [comment]
@DJBenson It looks to me like the release today has been built on stable channel (0.20.22f)- if you were on latest beta (0.22.3) I think there are a number of changes that will not have been included in the release.

**Comment by DJBenson** [comment]
@lloyda yeah you're right - I have beta versions turned on in my install and did not spot that the latest fix was on the 0.20 codebase when I was on 0.22. I'm going to revert to the previous beta with my fixes from #56 until the repository catches up.

**Comment by lloyda** [comment]
@mazzy89 

> interesting. I have updated to 2023.1.1 too and I do not have anymore that error. Further I do not see your error as well.

Have you fixed your error?  In which case you could close this issue.

**Comment by mazzy89** [comment]
Release notes wired https://github.com/zxdavb/ramses_cc/releases/tag/0.21.40
going to close this. thanks all
