### ISSUE TITLE
Vasco issue

### ISSUE THREAD

**Issue by kihotx** [zxdavb/ramses_cc#66]
Kindly ask for support with controlling Vasco D500 ventilation unit with RF (4 buttons) remote. 
I successfully configured ramses_cc with faking. I see packets from original RF transmitter:

058  I --- 29:083043 32:024669 --:------ 22F1 003 000206
060  I --- 29:083043 32:024669 --:------ 22F1 003 000306 
060  I --- 29:083043 32:024669 --:------ 22F1 003 000406 

in configuration.yaml i got faking device:

known_list:
    18:070952: {class: HGI}
    29:083043: {class: REM, faked: true}
    32:024669: {class: FAN, _note: D500}
    29:073042:
      class: REM
      faked: True
      commands:
        low:    ' I --- 29:073042 32:024669 --:------ 22F1 003 000206'
        medium: ' I --- 29:073042 32:024669 --:------ 22F1 003 000306'
        high:   ' I --- 29:073042 32:024669 --:------ 22F1 003 000406'

and using the command:

service: remote.send_command
data:
  command: max
target:
  entity_id: remote.29_083043

i see packet beeing transmited that exactly match that what were sniffed:

000  I --- 29:083043 32:024669 --:------ 22F1 003 000406

but ventilation unit is not reacting on any command. 
Could you please support, and advice what would be the potential root cause, and how it can be improved ?

Thanks!

**Comment by zxdavb** [comment]
I believe the answer is that you should be impersonating the existing switch, not faking a new switch - the FAN will only support one switch.

Do let me know if I am wrong.
