### ISSUE TITLE
Nuaire Drimaster PIV feature enhancement wishlist

### ISSUE THREAD

**Issue by jrb80** [zxdavb/ramses_cc#69]
The [Nuaire Drimaster PIV](https://www.nuaire.co.uk/residential-commercial-industrial-nuaire-products/nuaire-drimaster-positive-input-ventilation-systems?v=DRI-ECO-HEAT-HC+-+Heat+Model+Hall+Control) is supported by [ramses_cc](https://github.com/zxdavb/ramses_cc) but provides limited functionality and in my setup, the sensor entities don't provide any data/change values. That said, [Faking](https://github.com/zxdavb/ramses_cc/wiki/3.-Support-for-HVAC-systems#known-schemes-for-remotes) the wireless remote works brilliantly. The following commands are supported through faking;

Nuaire 4-way switch:
- Fan normal
- Fan boost (purge)
- Heater auto
- Heater off

I am suggesting some feature enhancement ideas for consideration, not all may be technically possible due to Nuaire's implementation. Unfortunately I am unable to help with coding but could help with the packet data collection and software testing! 

Sensors:
- Fan mode (Fan normal, Fan boost (purge), Heater auto, Heater off)
- Fan speed status - speed 0 (low) through to 6 (high) 
- Heater status (on/off)
- Filter status (clean/dirty)
- Runtime hours

Commands:
- Filter change reset 
- Fan speed change (0 through to 6)
- Standby mode (speed 0 turns fan "off")

The [Nuaire Remote Monitoring Device](http://www.nuaire.info/IandM/671790.pdf) confirms that runtime hours and filter status is reported by the Drimaster.

**Comment by zxdavb** [comment]
AFAIK (knew) - the Nuaire PIV should expose some sensors in HA via **ramses_cc** - I will look at this (after I have finished refactoring **evohome**.

I had a Drimaster Eco Heat HC, but it is crrently sitting in a box, due to last year's attic conversion.

In any case, I would love to see a packet log of the remote device interrogating the PIV - that information could expose new insights.

**Comment by zxdavb** [comment]
It appears the `31D9` & `31DA` packets do not contain this data (they could - there's space allocated in the payload, but these values never change).

Looks like we'll have to see what packets the DRI-ECO-RM send to the PIV!

**Comment by jrb80** [comment]
> It appears the `31D9` & `31DA` packets do not contain this data (they could - there's space allocated in the payload, but these values never change).

That's consistent with my experience, shame. It seems like only a partial (poor) protocol implementation by Nuaire.
