### ISSUE TITLE
Nuaire Drimaster PIV failing to do anything

### ISSUE THREAD

**Issue by ingus16** [zxdavb/ramses_cc#71]
Hi, 
Have 
- Nuaire Drimaster PIV 
- Nuaire DRI-ECO-4S (4-way switch)
- nanoCul 868 Mhz dongle with latest evofw3 based on P chip ( not u4)
- Home Assistant Supervised v11.1 Fresh install

The packet flew in and out, so nanocul with  HA is working.
Tried impersonate and faking, etc., seven days  12+ hours reading miles-long topics but no signs that anything is working. 

This is what shows in HA  Logs when using all buttons on the remote and PIV unit's response
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/d6bfec60-540e-4588-96be-6df751afe1b4)
This is my HA nanocull config
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/897bb314-1197-454d-9cf5-15846b1b71c0)
When trying to use commands via services like below 
Service call
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/8a4b4b5f-f035-4b49-97db-581beeca5b57)
Debug output
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/65e10776-1a5a-4c8e-91d9-928d2af7b987)

Tried to send a packet ( boost)
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/5bc9964e-5483-4f5e-9bb2-944758a79d58)
Debug
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/a4e3316d-b26e-4e35-ad8e-1762aa4af0b1)
and the outcome is - nothing happens

Some errors time after time appears, I have no idea what is about
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/855716e5-7b1e-44e8-85f5-5f2fc7520795)
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/601958ff-0a98-47c7-ad80-85a73ee58557)

Lovelace some strange things as well
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/026b25ca-5ea3-4f60-b067-3ab23dfc5bb5)

I have 0 idea how people managed to make it work with Nuaire Drimaster and at least fake a remote. 
Tried anything, 0 success., I assume that ramses_cc has bugs with the newest home assistant

**Comment by zxdavb** [comment]
Set a hint for the `30:071287` in the known list - it is of class FAN, not RFG.

Do you have the 4-way switch already bound, and you're simply trying to impersonate it?

The `must be exactly one command to learn` is a known bug - use the other version of **ramses_cc**.

But you should need to learn anything... as long as the switch is already bound.

As on the forum - others have got this working... as long as a switch is already bound, and you simply impersonate it.

A fix is coming for fully-faked switches...

**Comment by ingus16** [comment]
No matter which version I download Ramses_cc it always shows "TypeError: must be exactly one command to learn" when I send a command to test if impersonated or faked remote work.

**Comment by ingus16** [comment]
> Set a hint for the `30:071287` in the known list - it is of class FAN, not RFG.
> 
> Do you have the 4-way switch already bound, and you're simply trying to impersonate it?
> 
> The `must be exactly one command to learn` is a known bug - use the other version of **ramses_cc**.
> 
> But you should need to learn anything... as long as the switch is already bound.
> 
> As on the forum - others have got this working... as long as a switch is already bound, and you simply impersonate it.
> 
> A fix is coming for fully-faked switches...

No matter which version I download Ramses_cc it always shows "TypeError: must be exactly one command to learn" when I send a command to test if impersonated or faked remote work.
How can I properly impersonate the switch and use it via HA Please? Maybe I am doing something wrong is anywhere a quick start guide to look at ?

**Comment by ingus16** [comment]
Bought two controllers and no luck ..

**Comment by ingus16** [comment]
Tried to bind , as well no luck
![image](https://github.com/zxdavb/ramses_cc/assets/37122419/7d049f2d-bd56-4016-ad88-8f8abbeced01)

**Comment by ingus16** [comment]
If need any further logs details tests just let here know

**Comment by mogusbi** [comment]
Having the same issue with the Drimaster PIV. Trying to impersonate an already bound remote

```
[547168192448] Error handling message: Unknown error (unknown_error) Mo Gusbi from 2a00:23c7:e48d:f301:4868:70e4:4669:5a55 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 731, in handle_execute_script
    script_result = await script_obj.async_run(msg.get("variables"), context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ramses_cc/remote.py", line 216, in svc_send_command
    await self.async_learn_command(*args, **kwargs)
  File "/config/custom_components/ramses_cc/remote.py", line 135, in async_learn_command
    raise TypeError("must be exactly one command to learn")
TypeError: must be exactly one command to learn
```

**Comment by zxdavb** [comment]
https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/3080

**Comment by ingus16** [comment]
Hi, Unfortunately, there was no success in binding a fake ar impersonating the existing one. The same error always: "TypeError: must be exactly one command to learn."

**Comment by ingus16** [comment]
This can be closed. Please see the response to my question.
At the current date, for at least NUAIRE I should use system  service calls and not ramse_cc service calls
https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/3578?u=ingus16

**Comment by zxdavb** [comment]
The solution for v**0.20.x** and v**0.21.x** is to use:
```
service: remote.send_command
```
... instead of:
```
service: ramses_cc.send_command
```
